### ISSUE TITLE
dictplus 2021-11-17这个版本无法打开

### ISSUE THREAD

**Issue by Pinkuburu** [ahui2016/dictplus#1]
根据说明下载了dictplus-20211117.zip
执行了exe，可以启动
![image](https://user-images.githubusercontent.com/4962790/142160671-310b8557-7508-45b7-8599-ab656868c90a.png)
但无内容显示
![image](https://user-images.githubusercontent.com/4962790/142160732-bffb7362-f04b-4360-99ca-d7498b7f4b71.png)
浏览器版本
![image](https://user-images.githubusercontent.com/4962790/142160775-3b74b30e-0fee-441f-a6b0-8aa3c17464ec.png)
系统信息
![image](https://user-images.githubusercontent.com/4962790/142160805-36812c0e-bf19-4d09-ac4b-fde4a708aaa8.png)

**Comment by Pinkuburu** [comment]
切一台电脑就没有显示问题

**Comment by ahui2016** [comment]
如果有前端显示问题，可以试试在浏览器里按 Ctrl+Shift+R (三键同时按) 强制刷新。

**Comment by Pinkuburu** [comment]
![image](https://user-images.githubusercontent.com/4962790/142180394-8d472b7f-2a01-47a3-b263-cc5f98305753.png)
不知道信息是否有帮助

**Comment by ahui2016** [comment]
有个 MIME 问题，奇怪，我这边用 Chrome 打开能正确接收 "text/javascript" 格式呀。我怀疑是与你浏览器里安装的 Katakana Terminator 发生了端口冲突，你可以试试：

1. 禁用插件试试看；
2. 进 cmd 或 powershell 里, 进入 exe 文件所在的文件夹，用命令 ` .\dictplus.exe -addr 127.0.0.1:955` 启动程序，然后访问  127.0.0.1:955

**Comment by Pinkuburu** [comment]
![image](https://user-images.githubusercontent.com/4962790/142232188-f4921dee-3dad-48b1-9e05-95690b3ebfff.png)
已经取消了相关的油猴脚本
![image](https://user-images.githubusercontent.com/4962790/142232284-eef1ef88-0971-4cda-b301-816ab5d8d842.png)
打开后依旧没有内容
![image](https://user-images.githubusercontent.com/4962790/142232340-a3eca7ab-f4d5-4b39-8afb-313de7ad07cb.png)


（如果您还想排这个bug我可以陪您持续测试反馈……如果太麻烦就算了，反正目前下来就我这台电脑不行

**Comment by ahui2016** [comment]
非常感谢你的反馈！我刚刚更新了 html 文件，请下载 https://github.com/ahui2016/dictplus/archive/refs/heads/main.zip 把里面 public 文件夹里的 index.html, edit-word.html, word-info.html 这三个文件复制出来，覆盖你原有的旧文件。

如果这次也不行，那就暂时先不管了，等有更多人反映这个问题我再研究别的办法吧。

**Comment by Pinkuburu** [comment]
OKOK，了解
但我根据你的建议覆盖了文件，使用80以及自定义的端口进行测试后，依然无效。
我感觉应该不是代码的问题，应该是我系统之类的问题吧
![image](https://user-images.githubusercontent.com/4962790/142350945-9530a735-847e-4f03-8593-149e555788ab.png)

**Comment by BridanLSP** [comment]
我也遇到了相同的问题。我是win10，试过下载exe，也试过git clone，也试过你在这个贴子发的链接（后两者是我自己go build），然后也改过uddr，然后都是在浏览器显示空白。
Microsoft Edge
版本 96.0.1054.34 (官方内部版本) (64 位)

**Comment by ahui2016** [comment]
@Pinkuburu @BridanLSP 很可能是这个原因 https://github.com/labstack/echo/issues/1038 

简而言之，是一部分Windows系统的注册表对 .js 文件的类型判断出了问题。

我会尝试让后端强制加一个正确的 hearder，弄好了再通知两位，非常感谢反馈！

**Comment by BridanLSP** [comment]
> 好的

**Comment by ahui2016** [comment]
@Pinkuburu @BridanLSP 更新了，这次应该可以解决问题了，请看 README 的“更新”部分进行更新。

**Comment by BridanLSP** [comment]
> 问题已解决

**Comment by Pinkuburu** [comment]
十分感谢您，已经OK正常了。您辛苦了
![V{B2UGBLE$T9ESS73IU$M3](https://user-images.githubusercontent.com/4962790/144193427-a4bb0d87-347c-442f-b0d8-cc31d8f64aff.gif)
