### ISSUE TITLE
权限被拒绝

### ISSUE THREAD

**Issue by xp12047** [ahui2016/dictplus#2]
prefix":"echo","file":"main.go","line":"39  ","消息":"监听 tcp 127.0.0.1:80: 绑定: 权限被拒绝"}  
![Screenshot_20220516_170600_com termux](https://user-images.githubusercontent.com/56335408/168558690-38538cd1-4041-445e-9028-a0af19baaf6a.jpg)
这个该怎么处理啊？有点着急

**Comment by ahui2016** [comment]
可以使用参数 -addr 改端口，比如 ./dictplus -addr 127.0.0.1:8080 然后浏览器访问 127.0.0.1:8080

**Comment by xp12047** [comment]
> 参数使用 -addr 改端口，比如 ./dictplus -addr 127.0.0.1:8080 然后可以浏览器访问 127.0.0.1:8080

可以了，谢谢，一开始我也是这么做的端口我改成了80但不行，😄，现在可以了
